-- In-app notifications, generated by triggers so every write path (API,
-- backfills, future jobs) produces them consistently.
CREATE TABLE notifications (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    -- recipient
    user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    -- who triggered it
    actor_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    kind VARCHAR NOT NULL CHECK (kind IN ('follow', 'comment', 'reaction')),
    post_id UUID REFERENCES posts (id) ON DELETE CASCADE,
    comment_id UUID REFERENCES comments (id) ON DELETE CASCADE,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Covers the two hot queries: unread count and the (newest-first) list.
CREATE INDEX idx_notifications_user_unread ON notifications (user_id, is_read);
CREATE INDEX idx_notifications_user_created ON notifications (user_id, created_at DESC);

-- New follower.
CREATE OR REPLACE FUNCTION notify_on_follow()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO notifications (user_id, actor_id, kind)
    VALUES (NEW.followee_id, NEW.follower_id, 'follow');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER notify_on_follow_trigger
AFTER INSERT ON follows
FOR EACH ROW
EXECUTE FUNCTION notify_on_follow();

-- Comment on your post (direct post replies only; self-comments skipped).
CREATE OR REPLACE FUNCTION notify_on_comment()
RETURNS TRIGGER AS $$
DECLARE
    owner INT;
BEGIN
    IF NEW.reply_to_type = 'post' THEN
        SELECT user_id INTO owner FROM posts WHERE id = NEW.reply_to;
        IF owner IS NOT NULL AND owner <> NEW.user_id THEN
            INSERT INTO notifications (user_id, actor_id, kind, post_id, comment_id)
            VALUES (owner, NEW.user_id, 'comment', NEW.reply_to, NEW.id);
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER notify_on_comment_trigger
AFTER INSERT ON comments
FOR EACH ROW
EXECUTE FUNCTION notify_on_comment();

-- Reaction on your post (self-reactions skipped; comment reactions carry no
-- post_id).
CREATE OR REPLACE FUNCTION notify_on_reaction()
RETURNS TRIGGER AS $$
DECLARE
    owner INT;
BEGIN
    IF NEW.to_type = 'post' THEN
        SELECT user_id INTO owner FROM posts WHERE id = NEW.to_id;
        IF owner IS NOT NULL AND owner <> NEW.user_id THEN
            INSERT INTO notifications (user_id, actor_id, kind, post_id)
            VALUES (owner, NEW.user_id, 'reaction', NEW.to_id);
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER notify_on_reaction_trigger
AFTER INSERT ON reactions
FOR EACH ROW
EXECUTE FUNCTION notify_on_reaction();
