name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgres://postgres:password@localhost:5432/hello_rocket

jobs:
  check_system:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Show info of system
        run: free -h && lscpu && lshw

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install libgtk3
        run: apt-get update && apt-get install libgtk-3-dev && apt-get install pkg-config
      - uses: actions/checkout@v3
      - name: Check
        run: cargo check
      - name: Build
        run: cargo build --bin server --release
      - name: Check status of release binaries
        run: stat ./target/release/server

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: hello_rocket
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v3

      - name: Install libgtk3
        run: apt-get update && apt-get install libgtk-3-dev && apt-get install pkg-config
      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for postgres..."
            sleep 1
          done
      - name: Install Diesel CLI
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/diesel-rs/diesel/releases/download/v2.2.1/diesel_cli-installer.sh | sh

      - name: Database initialization
        run: cd ./backend/query && diesel setup && diesel database reset

      - name: Run tests
        run: cargo test --bin server
